//+1==========================================================================//
//  MODULE                      SORT.HPP                                      //
//============================================================================//
//  FUNCTION    Definition of general array-sorting functions
//  SYSTEM      IBM PC >= i386 cpu
//  SEE ALSO     SORT.CPP
//  PROGRAMMER  Allan Dystrup
//  VERSION     0.1
//  REFERENCES  coming soon
//  USAGE       "
//  DOC.
//  BUGS
//  COPYRIGHT   none!
//-1==========================================================================//



template <class Type>
void b_sort(Type *ia, int low, int high);


template <class Type>
void q_sort(Type *ia, int low, int high);



// END MODULE SORT.HPP
//============================================================================//
